settings:
  html: false
  anchor: false
  escape: false
  lockfile: false
  hide-empty: true
formatter: "markdown table"

sections:
  show:
    - requirements
    - providers
    - modules
    - data-sources
    - resources
    - inputs
    - outputs

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
